import type { TopicDefinition } from '../types/polymarket';

export const TOPIC_DEFINITIONS: TopicDefinition[] = [
  {
    id: 'us-iran',
    label: 'US-Iran War',
    description: 'Escalation, strikes, retaliation, diplomacy, and military posture.',
    accent: '#ff7b54',
    surface: 'rgba(255, 123, 84, 0.14)',
    keywords: [
      'iran',
      'tehran',
      'u.s. iran',
      'us iran',
      'us-iran',
      'american strike',
      'retaliation',
      'war',
      'conflict',
      'attack',
      'missile',
      'bomb',
      'ceasefire',
      'khamenei',
      'nuclear',
    ],
    aliases: ['iran', 'tehran', 'military', 'strike'],
  },
  {
    id: 'hormuz',
    label: 'Strait Of Hormuz',
    description: 'Closure risk, shipping disruptions, naval incidents, and oil routes.',
    accent: '#0fb7af',
    surface: 'rgba(15, 183, 175, 0.14)',
    keywords: [
      'strait of hormuz',
      'hormuz',
      'persian gulf',
      'shipping lane',
      'shipping',
      'tanker',
      'oil transit',
      'maritime',
      'naval',
      'gulf shipping',
    ],
    aliases: ['hormuz', 'shipping', 'tanker'],
  },
  {
    id: 'trump',
    label: 'Trump Actions',
    description: 'Executive actions, policy moves, tariffs, investigations, and White House decisions.',
    accent: '#f6c15b',
    surface: 'rgba(246, 193, 91, 0.14)',
    keywords: [
      'trump',
      'donald trump',
      'white house',
      'executive order',
      'administration',
      'tariff',
      'deport',
      'department',
      'lawsuit',
      'indict',
      'policy',
    ],
    aliases: ['trump', 'white house', 'administration'],
  },
  {
    id: 'fed',
    label: 'US Rates',
    description: 'Fed decisions, FOMC, cuts, hikes, Powell remarks, and rate path pricing.',
    accent: '#88c85b',
    surface: 'rgba(136, 200, 91, 0.14)',
    keywords: [
      'fed',
      'federal reserve',
      'fomc',
      'interest rate',
      'rate cut',
      'rate hike',
      'jerome powell',
      'powell',
      'central bank',
      'treasury yield',
    ],
    aliases: ['fed', 'fomc', 'powell'],
  },
];
